# Generated by Django 5.0.3 on 2024-05-03 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('spesifikasi', models.TextField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='HP1Jutaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hp_1jutaan', to='tokohp.hp')),
            ],
        ),
        migrations.CreateModel(
            name='HP2Jutaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hp_2jutaan', to='tokohp.hp')),
            ],
        ),
    ]
